from lib.transport.segments.segment import Segment

# SOCKET
BUFFER_SIZE = 1024
MAX_PACKET_SIZE = BUFFER_SIZE + Segment.HEADER_SIZE
TIMEOUT = 1

# NUMBER OF ATTEMPTS FOR HANDSHAKE
MAX_HSK_RETRIES = 5

# NUMBER OF ATTEMPTS FOR GBN
MAX_GBN_RETRIES = 10

# GBN
WINDOW_SIZE = 8
MAX_SEQ = 256

# PROTOCOL IDs
PROTOCOL_STOP_AND_WAIT = 0
PROTOCOL_GO_BACK_N = 1

# DYNAMIC TIMEOUT CONSTANTS
ALPHA = 0.125
BETA = 0.25

# LOG FILE NAME
SERVER_LOG_FILE = "app.log"
CLIENTS_LOG_FILE = "clients.log"