# SIZE LIMITS
BYTES_PER_MB = (1024 ** 2)
MAX_CLIENTS = 10
MAX_STORAGE_SIZE = 500 * BYTES_PER_MB   # Bytes
MAX_FILE_SIZE = 16 * BYTES_PER_MB     # Bytes

# FORMAT FOR RESPONSE SEGMENT
RES_FORMAT = "!BQ"

# STATUS CODES
CODE_READY = 100
ERR_NO_SPACE = 201
ERR_FILE_NOT_FOUND = 202
ERR_GENERIC = 200
ERR_SIZE_LIMIT_EXCEEDED = 203

# AMOUNT OF WORKER THREADS
WORKERS = 5