# IDs
SW_PROTOCOL_ID = 0
GBN_PROTOCOL_ID = 1

TYPE_ACK = 0
TYPE_DATA = 1
TYPE_FINISHED = 2
TYPE_HANDSHAKE_REQUEST = 3
TYPE_HANDSHAKE_RESPONSE = 4
TYPE_HANDSHAKE_READY = 5
TYPE_HANDSHAKE_ERROR = 6

# Socket
SKT_TIMEOUT = 2.0
SKT_BUFFER_SIZE = 1024

# Max retries
UPLOAD_MAX_RETRIES = 5
DOWNLOAD_MAX_RETRIES = 5

SW_MAX_RETRIES = 10

